services:
  uprint:
    build: .
    image: rluccadev/uprint:latest
    container_name: uprint
    network_mode: host
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
