version: "3.8"

services:
  uprint:
    build: .
    image: rluccadev/uprint:latest
    container_name: uprint
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
